### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by yukulele** [ibancg/lingot#14] opened 2018-12-09 20:27 UTC
GUI text is unreadable with dark theme

![lingot dark](https://user-images.githubusercontent.com/347244/49702514-27ebe680-fbf9-11e8-9401-67d3aca26085.png)

**Comment by ibancg** [comment] 2018-12-10 08:03
Hi, that's an old version of Lingot. Did you try a more recent one?. It works for me:

![41248741-36de1af8-6db2-11e8-8614-c4de7e17707f](https://user-images.githubusercontent.com/5263631/49718452-6d8ccb80-fc5a-11e8-8ff2-d8817be538a6.png)

**Comment by yukulele** [comment] 2018-12-10 08:30
I just install it from apt-get, it install v0.9.1

**Comment by ibancg** [comment] 2018-12-11 16:10
True, I can reproduce the problem with Lingot 0.9.1

![image](https://user-images.githubusercontent.com/5263631/49812435-b7160d00-fd65-11e8-983a-0a027b2d789a.png)

It is fixed in the latest release 1.0.1, though. You can build it from source, wait for it in your distribution, or try to install the package from a more recent distribution if the dependencies allow.

Here an overview of the deployment of version 1.0.1 over the different popular distributions: https://repology.org/metapackage/lingot/versions

Thanks for reporting the issue.

**Closed as completed by ibancg** 2018-12-11 16:10 UTC
